# Generated by Django 4.2 on 2023-08-13 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 13, 15, 5, 26, 344952, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
